[package]
name = "vivace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
uuid = { version = "1.11.0", features = ["v4", "fast-rng"] }
